name: Game Crash
description: My gamed crashed.
title: "[Game Crash] ADD TITLE HERE"

body:
  - type: textarea
    attributes:
      label: Describe the crash
      description: Describe how it crashed by giving us the following information.
      placeholder: |
        1. What you were doing before it crashed and what action made the game to crash.
        2. Upload the crashinfo.txt (GameFolder/crashinfo.txt)
        3. Upload the info.txt and log.txt (GameFolder/Logs)
    validations:
      required: true
  - type: textarea
    attributes:
      label: How can you reproduce the error?
      placeholder: |
        1. Start the game
        2. Go to screen '...'
        3. Select '...'
        4. Game crashed
    validations:
      required: true
  - type: textarea
    attributes:
      label: Screenshots/Videos
      description: If possible, take screenshots or record the crash happening.
  - type: dropdown
    id: gamemode
    attributes:
      label: Game Mode
      description: What Game Mode are you playing on?
      options:
        - dance
        - pump
        - smx
        - techno
        - be-mu
        - po-mu
        - gddm
        - gdgf
        - gh
        - taiko
        - para
        - kbx
        - ez2
        - ds3ddx
        - maniax
        - kickbox
        - stepstage
  - type: textarea
    attributes:
      label: Additional Information
      description: If there's any information that you think would help us.
