name: Unexpected Behavior
description: A function didn't behave as expected
title: "[Unexpected Behavior] ADD TITLE HERE"

body:
  - type: markdown
    attributes:
      value: |
        ***Before doing such issue, please make sure you're using the latest version of the game.***
    id: gamemode
    attributes:
      label: Game Mode
      description: What Game Mode are you playing on?
      options:
        - dance
        - pump
        - smx
        - techno
        - be-mu
        - po-mu
        - gddm
        - gdgf
        - gh
        - taiko
        - para
        - kbx
        - ez2
        - ds3ddx
        - maniax
        - kickbox
    validations:
      required: true
  - type: textarea
    id: theme
    attributes:
      label: Theme
      description: Please let us know what theme (and version) you are using.  
  - type: textarea
    attributes:
      label: What you're using
      description: Explain what function you're using and what arguments you're giving.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Expected behaviour
      description: Explain what you expected to happen or the function to return
    validations:
      required: true
